
export const POSTS_FETCH_REQUEST = 'SHOW_POSTS_FETCH_REQUEST';
export const POSTS_FETCHED = 'SHOW_POSTS_FETCHED';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP = 'SIGN_UP';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const POST_LIKE_REQUEST = 'POST_LIKE_REQUEST';
export const POST_LIKE_SUCCESS = 'POST_LIKE_SUCCESS';

export const LIKED_POSTS_REQUEST = 'LIKED_POSTS_REQUEST';
export const LIKED_POSTS_SUCCESS = 'LIKED_POSTS_SUCCESS';

export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';

// export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
// export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';